services:
  synergy:
    image: ghcr.io/madelynnsadie/synergy:latest
    network_mode: host
    volumes:
      - ./data:/synergydata
    environment:
      - SYNERGY_DATA=/synergydata/data.json
      - SYNERGY_PRIVATE_KEY=awesomekey